name: Build and Publish

on:
  push:
    branches: [ "task40" ]  # This should be the branch you merge into

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip uninstall bumpversion -y || true  # Ignore errors if not installed
        pip install bump2version build twine

    - name: Get current version
      run: bump2version --current-version `grep 'version =' pyproject.toml | sed 's/version = //g' | tr -d '"'` --dry-run --verbose patch

    - name: Bump patch version
      run: bump2version --verbose patch

    - name: Build Package
      run: |
        ./build.sh

    - name: Publish Package
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* --verbose --non-interactive --repository testpypi --username __token__ --password $PYPI_API_TOKEN
